name: actions
on:
  push:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.job }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ubuntu-core:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        QEMU_VER: [8.2.4+ds-1]
        DOCKER_REPO: [ghcr.io/amyspark/ubuntu-server]
        VERSION: ['20.04', '22.04', '23.10']
        UNAME_ARCH: [x86_64, arm64, armhf, ppc64el, s390x, riscv64]
        include:
          - {ARCH: amd64,   QEMU_ARCH: x86_64,  UNAME_ARCH: x86_64}
          - {ARCH: arm64,   QEMU_ARCH: aarch64, UNAME_ARCH: arm64}
          - {ARCH: armhf,   QEMU_ARCH: arm,     UNAME_ARCH: armhf}
          - {ARCH: ppc64el, QEMU_ARCH: ppc64,   UNAME_ARCH: ppc64el}
          - {ARCH: s390x,   QEMU_ARCH: s390x,   UNAME_ARCH: s390x}
          - {ARCH: riscv64,   QEMU_ARCH: riscv64,   UNAME_ARCH: riscv64}
        exclude:
          - {VERSION: '20.04',   UNAME_ARCH: riscv64}
          - {VERSION: '22.04',   UNAME_ARCH: riscv64}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set up Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ matrix.DOCKER_REPO }}
          tags: |
            type=raw,value=${{ matrix.UNAME_ARCH }}-${{ matrix.VERSION }}
      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Dockerfile
        run: |
          sudo ./update.sh -a ${{ matrix.ARCH }} -v ${{ matrix.VERSION }} -q ${{ matrix.QEMU_ARCH }} -u ${{ matrix.QEMU_VER }} -d ${{ matrix.DOCKER_REPO }} -t ${{ matrix.UNAME_ARCH }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/${{ matrix.ARCH }}
          push: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/main' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
