name: actions
on:
  push:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.job }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ubuntu-core:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        QEMU_VER: [v6.1.0-5]
        DOCKER_REPO: [ghcr.io/amyspark/ubuntu-core]
        VERSION: [trusty, xenial, bionic, focal, jammy]
        UNAME_ARCH: [x86_64, arm64, armhf, i386, ppc64el, s390x]
        include:
          - {ARCH: amd64,   QEMU_ARCH: x86_64,  UNAME_ARCH: x86_64}
          - {ARCH: arm64,   QEMU_ARCH: aarch64, UNAME_ARCH: arm64}
          - {ARCH: armhf,   QEMU_ARCH: arm,     UNAME_ARCH: armhf}
          - {ARCH: i386,    QEMU_ARCH: i386,    UNAME_ARCH: i386}
          - {ARCH: ppc64el, QEMU_ARCH: ppc64,   UNAME_ARCH: ppc64el}
          - {ARCH: s390x,   QEMU_ARCH: s390x,   UNAME_ARCH: s390x}
        exclude:
          - {VERSION: trusty,   UNAME_ARCH: s390x}
          - {VERSION: xenial,   UNAME_ARCH: s390x}
          - {VERSION: focal,    UNAME_ARCH: i386}
          - {VERSION: jammy,    UNAME_ARCH: i386}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set up Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ matrix.DOCKER_REPO }}
          tags: |
            type=raw,value=${{ matrix.UNAME_ARCH }}-${{ matrix.VERSION }}
      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Dockerfile
        run: |
          sudo add-apt-repository 'deb http://archive.ubuntu.com/ubuntu focal main universe'
          sudo apt-get update && sudo apt-get install -y qemu-user-static
          sudo ./update.sh -a ${{ matrix.ARCH }} -v ${{ matrix.VERSION }} -q ${{ matrix.QEMU_ARCH }} -u ${{ matrix.QEMU_VER }} -d ${{ matrix.DOCKER_REPO }} -t ${{ matrix.UNAME_ARCH }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/${{ matrix.ARCH }}
          push: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/master' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
